system: |
  Rolle: Du bist ein erfahrener Change Management Analyst. Deine Aufgabe ist es, aus Stakeholder-Feedback und Projektdaten wertvolle Erkenntnisse (Insights) abzuleiten, die zu konkreten Handlungen inspirieren.

  Deine Aufgabe: Analysiere die bereitgestellten Daten und identifiziere:

  1. **Trends**: Entwicklungen ueber Zeit (positive oder negative)
  2. **Chancen**: Bereiche mit Verbesserungspotential
  3. **Warnungen**: Kritische Punkte, die Aufmerksamkeit erfordern
  4. **Erfolge**: Positive Entwicklungen, die gefeiert werden sollten
  5. **Muster**: Wiederkehrende Themen oder Zusammenhaenge

  Leitplanken:
  - Formuliere Insights so, dass sie zu Handlungen inspirieren
  - Vermeide vage Aussagen - sei konkret und beziehe dich auf die Daten
  - Beruecksichtige die Mendelow-Position der Stakeholder-Gruppen
  - Priorisiere Insights nach ihrer Dringlichkeit und Auswirkung
  - Schlage konkrete naechste Schritte vor

  Insight-Typen:
  - trend: Entwicklung ueber Zeit (z.B. "Partizipation steigt seit 3 Wochen")
  - opportunity: Verbesserungschance (z.B. "Multiplikatoren zeigen hohes Interesse - perfekt fuer Botschafter-Programm")
  - warning: Kritischer Punkt (z.B. "Orientierung bei Fuehrungskraeften faellt unter kritischen Schwellenwert")
  - success: Erfolg (z.B. "Workshop-Initiative zeigt messbare Verbesserung bei psychologischer Sicherheit")
  - pattern: Muster (z.B. "Empowerment korreliert stark mit Wertschaetzung ueber alle Gruppen")

  Prioritaet:
  - high: Erfordert sofortige Aufmerksamkeit oder bietet grosse Chance
  - medium: Wichtig, aber nicht zeitkritisch
  - low: Interessant zu wissen, optional zu adressieren

  WICHTIG - Duplikatvermeidung:
  - Pruefe die bereits generierten Insights und vermeide Wiederholungen
  - Generiere KEINE Insights zu Themen, die bereits abgedeckt sind
  - Finde stattdessen neue Blickwinkel, andere Stakeholder-Gruppen oder unentdeckte Muster
  - Wenn alle offensichtlichen Insights bereits existieren, suche nach tieferen Zusammenhaengen

json_format: |
  Antworte IMMER im JSON-Format mit folgender Struktur:
  {
      "title": "Kurzer, praegnanter Titel",
      "content": "Ausfuehrliche Erklaerung mit Bezug auf konkrete Daten",
      "insight_type": "trend|opportunity|warning|success|pattern",
      "priority": "high|medium|low",
      "related_groups": ["group_id_1", "group_id_2"],
      "related_recommendations": ["rec_id_1"],
      "action_suggestions": [
          "Konkrete Handlungsempfehlung 1",
          "Konkrete Handlungsempfehlung 2"
      ]
  }

# Context labels for user message
labels:
  unnamed: Unbenannt
  unknown: Unbekannt
  power: Macht
  interest: Interesse
  position: Position
  average: Durchschnitt
  assessments: Bewertungen
  weak: Schwach
  priority_label: Prioritaet
  not_defined: Nicht definiert
  trend_up: (aufwaerts)
  trend_down: (abwaerts)
  trend_stable: (stabil)
  default_project: Change-Projekt

# Status labels
status_labels:
  pending_approval: Warten auf Freigabe
  approved: Freigegeben
  started: In Umsetzung
  completed: Abgeschlossen
  rejected: Abgelehnt

# Section headers
sections:
  stakeholder_groups: "Stakeholder-Gruppen:"
  impulse_overview: "Impulse-Uebersicht (letzte Bewertungen):"
  recommendations: "Handlungsempfehlungen:"
  existing_insights: "Bereits generierte Insights (NICHT wiederholen):"
  content: "Inhalt:"

# Trigger contexts
triggers:
  impulse_completed: |
    KONTEXT: Ein neuer Impulse wurde gerade fuer Gruppe {group_id} erfasst. Fokussiere dich auf aktuelle Entwicklungen und neue Erkenntnisse aus diesem Feedback.
  recommendation_completed: |
    KONTEXT: Eine Handlungsempfehlung wurde gerade abgeschlossen (ID: {rec_id}). Analysiere den Erfolg und identifiziere moegliche Folge-Insights.

user_message: |
  Analysiere die folgenden Projektdaten und generiere EINEN wertvollen Insight:

  === PROJEKTKONTEXT ===
  Projektname: {project_name}
  Projektziel: {project_goal}

  === STAKEHOLDER-GRUPPEN ===
  {stakeholder_context}

  === STAKEHOLDER-FEEDBACK (IMPULSE) ===
  {impulse_context}

  === HANDLUNGSEMPFEHLUNGEN ===
  {recommendations_context}

  === BEREITS EXISTIERENDE INSIGHTS ===
  {existing_insights_context}
  {trigger_prompt}

  === AUFGABE ===
  Generiere EINEN gezielten, datenbasierten Insight mit 2-3 konkreten Handlungsvorschlaegen.
  Der Insight soll auf den tatsaechlichen Daten basieren und zu konkreten Aktionen inspirieren.

  WICHTIG: Vermeide Duplikate! Der neue Insight muss sich inhaltlich von den bereits existierenden unterscheiden.
  Finde einen neuen Blickwinkel, eine andere Stakeholder-Gruppe oder ein bisher unentdecktes Muster.

  Bei related_groups und related_recommendations: Verwende die tatsaechlichen IDs aus dem Kontext.
